# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: arahansen
email: andrew.hansen.ra@gmail.com
description: I'm a web developer that loves to build beautiful software using awesome technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: arahansen
github_username:  arahansen

# Build settings
markdown: kramdown

# Author info
author_image: "/assets/images/profile.jpeg"

# Permalinks
permalink: none
